### PR TITLE
Fix garnish import 

### PR DESCRIPTION
**Pull request by a-ws-m**
Correct the garnish import to solve issue #4

### CODE REVIEW

**Review by brisvag — APPROVED** [review]
Thanks! This project has been sitting alone here for a while, I'm surprised to see someone using it :) Is it still working in your hands?

**Comment by a-ws-m** [comment]
No problem :) I've just been getting into molecular dynamics research and have been scoping several packages to see what works for me, and this one popped up in the process. The basic functionality was working, after this change. However, I think I'll migrate to something other than PyMol, as I don't have a license and prefer FOSS where possible.
Thanks for taking the time to make the package, though!

**Comment by brisvag** [comment]
I was using [pymol-open-source](https://github.com/schrodinger/pymol-open-source) at the time, in case you are not aware, but I don't know what's the status currently :)

**Comment by pacho2** [comment]
Do you have any recommended alternative? I mostly use vmd... but it seems that we still need to rely on some old extra scripts to make it work with martini :/ 

Thanks

**Comment by brisvag** [comment]
I'll bring in @mjtadema, he's more on top of these things these days :)

**Review by brisvag — APPROVED** [review]

**Comment by a-ws-m** [comment]
@pacho2 not sure which scripts you're using but I've found the easiest way to work with most visualisation libraries is to convert the `.gro` file to a `.pdb` file:

```bash
#!/bin/bash
gro_file="$1"
tpr_file="$2"
out_file="$3"

echo 0 | gmx trjconv -f $gro_file -s $tpr_file -conect -o $out_file -pbc mol
sed -i '/ENDMDL/d' $out_file
```

Recently I've been using the free version of Ovito because the GUI of VMD was buggy on my machine and I got fed up of the CLI (no tab autocomplete and I couldn't use arrow keys to access command history). Mol* (https://molstar.org/) is an interesting open-source alternative but it's a lot more limited. There's a VSCode extension called protein viewer (https://marketplace.visualstudio.com/items?itemName=ArianJamasb.protein-viewer) which wraps Mol* - very useful for quickly checking things on remote machines.

**Comment by pacho2** [comment]
Thanks! I tried to convert to PDB... but the files can sometimes become too big for my cases. Thanks for the suggestions, I will give Ovito a try.

For VMD, I tried to find the "do_vmd" script mentioned at  http://md.chem.rug.nl/index.php/tutorials-general-introduction-gmx5/82-tutorial2-gmx5?start=7 , but it seems it's not currently available :/

**Pull request merged**
